### ISSUE TITLE
Got "microsoft.com/directx: 0" after following the steps

### ISSUE THREAD

**Issue by calvin197** [marosset/aks-windows-gpu-acceleration#2]
I encountered an issue while following the provided steps. In the "Node Setup Verification" step, both Capacity and Allocatable for "microsoft.com/directx" showed as "0." I utilized the command below to include a node pool named "gpunp3" with the "standard_nv12" VM using Windows Server 2022:

`az aks nodepool add --resource-group calvinshumrg --cluster-name calvinshumCluster1 --os-type Windows --os-sku Windows2019 --name gpunp3 --node-count 1 --node-vm-size standard_nv12`

I repeated the same steps with Windows Server 2019 and encountered the same issue.

I would appreciate any insights or suggestions regarding the cause of this issue.

![image](https://github.com/marosset/aks-windows-gpu-acceleration/assets/44663669/04de38be-9ee2-4805-8ca4-cc16060c1562)

------------------------------------------------------------

**My current investigation:**

I suspect that the NVIDIA GPU Driver Extension for Windows may not have been installed correctly, given that the AKS OS-IMAGE being used is Windows Server 2019/ 2022 Datacenter instead of the Core version specified in the documentation.

![image](https://github.com/marosset/aks-windows-gpu-acceleration/assets/44663669/7dd202af-fe76-43a0-aea4-7e7fe0443922)

According to the [NVIDIA GPU Driver Extension for Windows](https://learn.microsoft.com/en-us/azure/virtual-machines/extensions/hpccompute-gpu-windows), the extension supports the Core version of both Windows Server 2019 and Windows Server 2022. However, it is unclear whether the extension is also compatible with the Datacenter version.

Could you please provide some insights on whether the NVIDIA GPU Driver Extension is expected to function properly with the Datacenter version as well?

![image](https://github.com/marosset/aks-windows-gpu-acceleration/assets/44663669/eafc971e-0931-40e2-91e0-cdf273778b5c)

**Comment by calvin197** [comment]
I retried the steps again today and got the same result. I did a further investigation by ssh into the VM. Here's my finding:

In [the official doc](https://learn.microsoft.com/en-us/azure/virtual-machines/extensions/hpccompute-gpu-windows#review-output-logs), it states that:
![image](https://github.com/marosset/aks-windows-gpu-acceleration/assets/44663669/97718a67-d1d2-4ddd-8017-c6535c7a8087)

However, I can't find the directory C:\WindowsAzure\Logs\Plugins\Microsoft.HpcCompute.NvidiaGpuDriverWindows\ 

![image](https://github.com/marosset/aks-windows-gpu-acceleration/assets/44663669/53c1a127-2ec6-4bbb-8586-7bc5b4154083)

**Comment by pineapplethevoyager** [comment]
Solution: update the vmss after installing the NVIDIA GPU Extension by running 
![image](https://github.com/marosset/aks-windows-gpu-acceleration/assets/91150577/f93ea8c6-e5c9-43b3-abc4-615ef963e342)

Then be patient as it may take some time for the driver to actually spin up!
